spring.application.name=BookCrud
server.port=8080

# Cấu hình kết nối PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5433/book
spring.datasource.username=postgres
spring.datasource.password=It123456!
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình map tên cột từ snake_case (DB) sang camelCase (Java) cho MyBatis
mybatis.configuration.map-underscore-to-camel-case=true
