spring.application.name=BookCrud
server.port=8080

# Cấu hình kết nối PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5433/book
spring.datasource.username=postgres
spring.datasource.password=It123456!
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình map tên cột từ snake_case (DB) sang camelCase (Java) cho MyBatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml

# Đường dẫn để truy cập giao diện giao diện Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Đường dẫn xuất file cấu hình API dạng JSON chuẩn OpenAPI 3
springdoc.api-docs.path=/api-docs

# Sắp xếp các API theo thứ tự bảng chữ cái hoặc phương thức (Alpha) để dễ nhìn
springdoc.swagger-ui.operationsSorter=alpha
