-------ブック テーブル--------------
DROP TABLE BOOK CASCADE
;
CREATE TABLE BOOK
(
    ID  INTEGER, --ブックID
    AUTHOR  VARCHAR(50), --著者名
    TITLE  VARCHAR(100), --タイトル
    POINT  INTEGER, --評価ポイント
    BOOKCOMMENT  TEXT, --評価コメント
    LASTUPDATE  TIMESTAMP --更新日時
)
;
ALTER TABLE BOOK
    ADD CONSTRAINT PK_BOOK01 PRIMARY KEY ( ID )
;

-------BOOK_SEQ シーケンス-------
DROP SEQUENCE BOOK_SEQ CASCADE
;
CREATE SEQUENCE BOOK_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999
    START WITH 1
    CYCLE
;
